name: Deploy to Cloud Run

env:
  SERVICE_NAME: plantcare-api
  DOCKER_IMAGE_URL: gcr.io/${{ secrets.GCP_PROJECT_ID }}/plantcare-api

on:
  push:
    branches:
      - dev-cc
  pull_request:
    branches:
      - dev-cc

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile .
          echo "Pushing Docker image..."
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run service: $SERVICE_NAME"
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region asia-southeast2 \
            --allow-unauthenticated
