name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'dev-cc'

env:
  PROJECT_ID: 'plantcare-443106' # Update to your Google Cloud project ID
  REGION: 'asia-southeast2' # Update to your region
  SERVICE: 'plantcare-api' # Update to your service name
  WORKLOAD_IDENTITY_PROVIDER: 'projects/920676430522/locations/global/workloadIdentityPools/github-pool/providers/github' # Update to your workload identity provider

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4' # Updated to the latest version

      # Authenticate to Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          project_id: '${{ env.PROJECT_ID }}'

      # Build and Deploy to Cloud Run
      - name: 'Build and Deploy to Cloud Run'
        run: |
          # Build the Docker image
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} .
          
          # Deploy the image to Cloud Run
          gcloud run deploy ${{ env.SERVICE }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated

      # Show output
      - name: 'Show output'
        run: |
          echo "Deployed to Cloud Run: https://${{ env.SERVICE }}-${{ env.REGION }}.run.app"
