name: Deploy to Cloud Run

env:
  SERVICE_NAME: plantcare-api
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  
  REPOSITORY_NAME: plantcare-api 
  DOCKER_IMAGE_URL: asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/plantcare-api /api:${{ github.sha }}
  
on:
  push:
    branches:
      - dev-cc
  pull_request:
    branches:
      - dev-cc

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Create Artifact Registry Repository
        run: |
          echo "Checking if Artifact Registry repository exists..."
          if ! gcloud artifacts repositories describe $REPOSITORY_NAME --location=asia-southeast2; then
            echo "Creating Artifact Registry repository..."
            gcloud artifacts repositories create $REPOSITORY_NAME \
              --repository-format=docker \
              --location=asia-southeast2 \
              --description="Docker repository for plantcare-api"
          else
            echo "Artifact Registry repository already exists."
          fi

      - name: Configure Docker Authentication
        run: |
          echo "Authenticating Docker to Google Cloud..."
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin asia-southeast2-docker.pkg.dev

      - name: Debug Docker Image URL
        run: |
          echo "Docker Image URL: ${{ env.DOCKER_IMAGE_URL }}"

      - name: Build and Push Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.DOCKER_IMAGE_URL }} -f Dockerfile .
          echo "Pushing Docker image..."
          docker push ${{ env.DOCKER_IMAGE_URL }}

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run service: $SERVICE_NAME"
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }} \
            --platform managed \
            --region asia-southeast2 \
            --allow-unauthenticated
