name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev-cc  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Google Cloud Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'  
        project_id: '${{ secrets.GCP_PROJECT_ID }}'     

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure Docker to use Google Cloud
      run: |
        echo "Configuring Docker to use Google Cloud..."
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }} .

    - name: Push Docker image to GCR
      run: |
        echo "Pushing Docker image to Google Container Registry..."
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}

    - name: Deploy to Cloud Run
      run: |
        echo "Deploying to Cloud Run..."
        gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }} \
          --platform managed \
          --region asia-southeast2 \
          --allow-unauthenticated
