name: Deploy to Cloud Run

env:
  SERVICE_NAME: plantcare-api
  PROJECT_ID: plantcare-443106
  REGION: asia-southeast2

on:
  push:
    branches:
      - dev-cc
  pull_request:
    branches:
      - dev-cc

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated
