name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - dev-cc

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: 'Docker Auth'
        uses: docker/login-action@v3
        with:
          username: 'oauth2accesstoken'
          password: '${{ secrets.GCP_SA_KEY }}'
          registry: '${{ secrets.GCP_REGION }}-docker.pkg.dev'

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/plantcare-api/${{ secrets.GCP_SERVICE_NAME }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/plantcare-api/${{ secrets.GCP_SERVICE_NAME }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.2.0
        with: 
          service: ${{ secrets.GCP_SERVICE_NAME }}
          image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/plantcare-api/${{ secrets.GCP_SERVICE_NAME }}  # Specify the image to deploy
          region: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Ensure project ID is specified